from research_agent import research_topic
from data_processor_agent import process_data
import os

def content_creation_workflow(topic: str, output_dir: str = "output") -> dict:
    """Execute sequential content creation workflow"""
    print(f"\n=== Starting Content Creation Workflow for: {topic} ===")
    
    # Step 1: Research Agent gathers information
    print("Step 1: Researching topic...")
    research_result = research_topic(topic)
    
    if research_result["status"] != "completed":
        return {"status": "error", "message": "Research failed"}
    
    # Step 2: Data Processor Agent structures the findings
    print("Step 2: Structuring findings...")
    structure_task = {
        "operation": "structure_findings",
        "findings": research_result["findings"],
        "format": "json"
    }
    structure_result = process_data(structure_task)
    
    if structure_result["status"] != "completed":
        return {"status": "error", "message": "Data structuring failed"}
    
    # Step 3: Create directory structure directly
    print("Step 3: Creating directory structure...")
    os.makedirs(f"{output_dir}/research", exist_ok=True)
    os.makedirs(f"{output_dir}/structured_data", exist_ok=True)
    os.makedirs(f"{output_dir}/final_content", exist_ok=True)
    
    # Step 4: Save research data directly
    print("Step 4: Saving research data...")
    with open(f"{output_dir}/research/raw_research.txt", 'w', encoding='utf-8') as f:
        f.write(str(research_result["findings"]))
    
    # Step 5: Save structured data directly
    print("Step 5: Saving structured data...")
    with open(f"{output_dir}/structured_data/processed_data.json", 'w', encoding='utf-8') as f:
        f.write(str(structure_result["result"]))
    
    # Step 6: Create final content document
    print("Step 6: Creating final document...")
    final_content = create_final_document(topic, research_result, structure_result)
    with open(f"{output_dir}/final_content/content_document.md", 'w', encoding='utf-8') as f:
        f.write(final_content)
    
    print(f"=== Content Creation Workflow Completed ===\n")
    
    return {
        "status": "completed",
        "topic": topic,
        "output_directory": output_dir,
        "files_created": [
            f"{output_dir}/research/raw_research.txt",
            f"{output_dir}/structured_data/processed_data.json",
            f"{output_dir}/final_content/content_document.md"
        ],
        "summary": f"Content creation completed for '{topic}'"
    }

def create_final_document(topic: str, research_result: dict, structure_result: dict) -> str:
    """Create final markdown document"""
    content = f"""# {topic}

## Research Summary
{research_result.get('findings', 'No findings available')}

## Structured Data Processing
{structure_result.get('result', 'No structured data available')}

## Conclusion
This document contains comprehensive research and structured data for the topic: {topic}.
Generated through sequential agent workflow execution using Strands Agents.

### Workflow Steps:
1. Research Agent gathered information
2. Data Processor Agent structured findings
3. File Manager Agent organized documentation

Generated by: Sequential Content Creation Workflow
"""
    
    return content

if __name__ == "__main__":
    # Example usage
    result = content_creation_workflow("Artificial Intelligence in Healthcare", "ai_healthcare_output")
    print("Workflow Result:", result)